apiVersion: v1
kind: Pod
metadata:
  name: service-app
  labels:
    name: service-app
spec:
  containers:
  - name: service-ap
    image: redis:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 6379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-app
spec:
  selector:
    matchLabels:
      app: service-app
  template:
    metadata:
      labels:
        app: service-app
    spec:
      containers:
      - name: service-app
        image: redis:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: service-app
spec:
  selector:
    app: service-app
  ports:
  - port: 6379
    targetPort: 6379

