version: '3.8'
services:

  redis:
    image: redis:7.0.0-alpine
    container_name: redis
    ports:
      - 6379
    networks:
      - app-tier
    restart: unless-stopped
  backend:
    build:
      context: ./src/
      dockerfile: Dockerfile
    depends_on:
      - redis
    networks:
      - app-tier
    #restart: unless-stopped

networks:
  app-tier:
    driver: bridge